import Head from "next/head";
import { useState } from "react";

type TState = "READY" | "STAGING" | "EXECUTE";

export default function Home() {
  // state -> 첫 drag and drop 화면 -> 파일 대기중 -> 제출하면 보여줌
  const [currentState, setCurrentState] = useState<TState>("READY");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-y h-screen min-h-screen w-full">
        <div className="mx-auto py-8 text-center text-3xl font-bold text-emerald-700 underline underline-offset-2 dark:text-emerald-500">
          Excel Analyzer
        </div>
        {currentState === "READY" && <></>}
        {currentState === "STAGING" && <></>}
        {currentState === "EXECUTE" && <></>}
      </div>
    </>
  );
}
